_BASE_: Base-Streethazard-ft.yaml
OUTPUT_DIR: "/home/shyam/Mask2Anomaly/output/streethazard-swin-base-coco-supervised/"
INPUT:
  CROP:
    SIZE: (380, 760) #default: (512,1024) 
MODEL:
  SEM_SEG_HEAD:
    IGNORE_VALUE: 12
    NUM_CLASSES: 12
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]