apiVersion: batch/v1
kind: Job
metadata:
  name: ex5-ood-datasets-vanilla2
  namespace: nil
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ex5-ood-datasets-vanilla2
          image: nil
          stdin: true
          tty: true
          volumeMounts:
            - name: gcp-credentials
              mountPath: /etc/gcp
              readOnly: true
            - mountPath: /dev/shm
              name: shared-memory-hack
          args:
            [
                "python3","rpl.code/main.py",
                "--dgx",
                "--gpus=1",
                "--online",
                "--gcloud"
            ]
          resources:
            limits:
              nvidia.com/gpu: 1
              memory: 120Gi
              cpu: 6000m
            requests:
              memory: 120Gi
              cpu: 6000m
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/gcp/credentials.json

      volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp
            items:
              - key: data-manager
                path: credentials.json
        - name: shared-memory-hack
          emptyDir:
            medium: Memory

